    def create_login_payload(open_id, access_token, platform):
        p = str(platform)
        random_ip = f"1{random.randint(0,9)}{random.randint(0,9)}.{random.randint(1,255)}.{random.randint(1,255)}.{random.randint(1,255)}"
        random_device = f"Google|{str(uuid.uuid4())}"

        payload = bytearray()
        payload.extend(SimpleProtobuf.encode_string(3,  datetime.now().strftime("%Y-%m-%d %H:%M:%S")))
        payload.extend(SimpleProtobuf.encode_string(4,  "free fire"))
        payload.extend(SimpleProtobuf.encode_int32 (5,  1))
        payload.extend(SimpleProtobuf.encode_string(7,  "1.123.1"))
        payload.extend(SimpleProtobuf.encode_string(8,  "Android OS 11 / API-30 (RP1A.200720.012/G991BXXU3AUL1)"))
        payload.extend(SimpleProtobuf.encode_string(9,  "Handheld"))
        payload.extend(SimpleProtobuf.encode_string(10, "we"))
        payload.extend(SimpleProtobuf.encode_string(11, "WIFI"))
        payload.extend(SimpleProtobuf.encode_int32 (12, 2400))
        payload.extend(SimpleProtobuf.encode_int32 (13, 1080))
        payload.extend(SimpleProtobuf.encode_string(14, "560"))
        payload.extend(SimpleProtobuf.encode_string(15, "ARM64 FP ASIMD AES | 8192 | 8"))
        payload.extend(SimpleProtobuf.encode_int32 (16, 3328))
        payload.extend(SimpleProtobuf.encode_string(17, "Adreno (TM) 640"))
        payload.extend(SimpleProtobuf.encode_string(18, "OpenGL ES 3.2 V@0490.0 (GIT@f51fd3a, Ia8bab3e8c8, 1602597876) (Date:10/13/20)"))
        payload.extend(SimpleProtobuf.encode_string(19, random_device))
        payload.extend(SimpleProtobuf.encode_string(20, random_ip))
        payload.extend(SimpleProtobuf.encode_string(21, "en"))
        payload.extend(SimpleProtobuf.encode_string(22, open_id))
        payload.extend(SimpleProtobuf.encode_string(23, p))
        payload.extend(SimpleProtobuf.encode_string(24, "Handheld"))
        payload.extend(SimpleProtobuf.encode_string(25, "samsung SM-G991B"))
        payload.extend(SimpleProtobuf.encode_string(29, access_token))
        payload.extend(SimpleProtobuf.encode_int32 (30, 1))
        payload.extend(SimpleProtobuf.encode_string(41, "we"))
        payload.extend(SimpleProtobuf.encode_string(42, "WIFI"))
        payload.extend(SimpleProtobuf.encode_string(57, "6122cc6c5071fcca2413506ce82f13e4"))
        payload.extend(SimpleProtobuf.encode_int32 (60, 22394))
        payload.extend(SimpleProtobuf.encode_int32 (61, 1424))
        payload.extend(SimpleProtobuf.encode_int32 (62, 3349))
        payload.extend(SimpleProtobuf.encode_int32 (63, 24))
        payload.extend(SimpleProtobuf.encode_int32 (64, 1552))
        payload.extend(SimpleProtobuf.encode_int32 (65, 22394))
        payload.extend(SimpleProtobuf.encode_int32 (66, 1552))
        payload.extend(SimpleProtobuf.encode_int32 (67, 22394))
        payload.extend(SimpleProtobuf.encode_int32 (73, 1))
        payload.extend(SimpleProtobuf.encode_string(74, "/data/app/~~lqYdjEs9bd43CagTaQ9JPg==/com.dts.freefireth-i72Sh_-sI0zZHs5Bw6aufg==/lib/arm64"))
        payload.extend(SimpleProtobuf.encode_int32 (76, 2))
        payload.extend(SimpleProtobuf.encode_string(77, "6122cc6c5071fcca2413506ce82f13e4|/data/app/~~lqYdjEs9bd43CagTaQ9JPg==/com.dts.freefireth-i72Sh_-sI0zZHs5Bw6aufg==/base.apk"))
        payload.extend(SimpleProtobuf.encode_int32 (78, 2))
        payload.extend(SimpleProtobuf.encode_int32 (79, 2))
        payload.extend(SimpleProtobuf.encode_string(81, "64"))
        payload.extend(SimpleProtobuf.encode_string(83, "2019120270"))
        payload.extend(SimpleProtobuf.encode_int32 (85, 1))
        payload.extend(SimpleProtobuf.encode_string(86, "OpenGLES3"))
        payload.extend(SimpleProtobuf.encode_int32 (87, 16383))
        payload.extend(SimpleProtobuf.encode_int32 (88, 4))
        payload.extend(SimpleProtobuf.encode_string(90, "Damanhur"))
        payload.extend(SimpleProtobuf.encode_string(91, "BH"))
        payload.extend(SimpleProtobuf.encode_int32 (92, 31095))
        payload.extend(SimpleProtobuf.encode_string(93, "android"))
        payload.extend(SimpleProtobuf.encode_string(94, "MIIFhjCCA26gAwIBAgIUVCQdTKC364qgxvKKn15UMOLnM0wwDQYJKoZIhvcNAQELBQAwdDELMAkGA1UEBhMCVVMxEzARBgNVBAgTCkNhbGlmb3JuaWExFjAUBgNVBAcTDU1vdW50YWluIFZpZXcxFDASBgNVBAoTC0dvb2dsZSBJbmMuMRAwDgYDVQQLEwdBbmRyb2lkMRAwDgYDVQQDEwdBbmRyb2lkMB4XDTE3MDkyODEwMDgyNloXDTQ3MDkyODEwMDgyNlowdDELMAkGA1UEBhMCVVMxEzARBgNVBAgTCkNhbGlmb3JuaWExFjAUBgNVBAcTDU1vdW50YWluIFZpZXcxFDASBgNVBAoTC0dvb2dsZSBJbmMuMRAwDgYDVQQLEwdBbmRyb2lkMRAwDgYDVQQDEwdBbmRyb2lkMIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAvylTyLEk6kqvaTtO+5+GW/sQ8P2yhsXpDiuRSQis56yl8UMR8mx8roLnnTU/mv8sKBf8Y811Z5BBBTaty/305IMnx5Exl/fE30atgemNjt66wGFio1wT1qhTPgK1qZYRTBpGIAcADd1g6xfw5ujF00XfzeOQBRWmYPioCpWI9tK+VayHk6jU09I9Y1TNUz5D76X4y7WQjIotpFRP8y9dzZJPG7Nh+RYbQdW2RxD10NITD6FQdRanWFRJP5YCQEMN/SGGdPnfCetDxXLwSVGdTfsWwTWrYBueMTUlFBSZDgSt8MXW1R9bF5UUEiz74OiZNONhx1LRrydyTDC3O/K0LaJ8d6s+Dyfonq4bRF4UQ0C/tQtJtz5XTkmY9wsscLekZ+TDwHKEP0m0j7pktBq54Bdr+TNPlyQ/NaWr4SeKiLbFEDfIPy5XoOcJX3anIjw4sm2xPr4YST8zDcnNFiq4RkMdOyyumxapasD0JSTslQu1MjLBH7S1QdNLIU+EByyjd5X9wtLww40jHxcPLUihb0glIJTg6YTWKDIg9dcJ/gc7uSSaqjG8cX86wBTaleV32x+gYtFxy4SNIEiwevP0zFirhTcQ7eJvfDvtyMqnpDUHzvTmvddyekQuWOr2Lmh0ZnBWb8H93heQcrr7gOUgi/DZS6MwMRK8fy6nQT39RzsCAwEAAaMQMA4wDAYDVR0TBAUwAwEB/zANBgkqhkiG9w0BAQsFAAOCAgEAP+WSvrwEWPjLMWyIB8KfPjkWMgPf+6/SWhw1Yj0Fnoo430rcmDw9YHInJXvDxW8gSOfxxzKzENLFQEQl08K7htiEI7lDPHqdrjV615cV+tzrTM5mX4i0jbZ3zKDBrY8pHbzvrPuaZm5Nk4N06L+jsLDkzPq/gUKdGLSjiYK32asOduq4ILNlh2QFJkQm/cFZw71c+UWNDiLQ2PX1644e9/Akzh5X4X2lMA4yAGWDRhFFzbdDCGlsUkD/3qxvN1O3k82YIzYQKrpN9c9J3lvnDDKzpwNptZRLB+mWej637FWrByRygbxzqAjtfhPoGW7Kd6vvRtvVGlyCJzYMMhtZPnmHRqCaGzo9MKh+9IICDCDWt4u2HR4QcYCAsZeCJE3gkP4vnqLp3y2BqOisZHgIB94MlUeTzJOLLHY+jIdr9sKDGvtgy5FHwdd8aCHxRvjNF2W/oDnWX7mVPcwueGbToEszvoP0hbEqgJIOHGGgLIjQ7+0gqkT/az3owaP/KNRtkDpoRXCA8aSCjC+UyY01qnj/rS4l9IAxIthSqf6BYEUWnL53KpQWuYVHq5CNEjjnM/0LKIvTh1wIDQCCtfn9Hwp6cud2LYafRKgOZekqb/UlZGf/LJ1vkBKvIr48xLRCDHeRW5kuPFBZISMfSR/KRjIQTCn07fbXunufqeJ868c="))
        payload.extend(SimpleProtobuf.encode_int32 (97, 1))
        payload.extend(SimpleProtobuf.encode_int32 (98, 1))
        payload.extend(SimpleProtobuf.encode_string(99,  p))
        payload.extend(SimpleProtobuf.encode_string(100, p))
        payload.extend(SimpleProtobuf.encode_string(102, ""))
        return bytes(payload)